DHAV_MAGIC = b"DHAV"
DHAV_FOOTER_MAGIC = b"dhav"
HEADER_SIZE = 24
FOOTER_SIZE = 8
MIB = 1024 * 1024
MIN_DECLARED_SIZE_DEFAULT = HEADER_SIZE
MAX_DECLARED_SIZE_DEFAULT = 10 * MIB
FRAME_TYPE_NAMES = {
    0xFC: "VIDEO_P_OR_SECONDARY",
    0xFD: "VIDEO_I_OR_PRIMARY",
    0xF0: "AUDIO",
    0xF1: "AUXILIARY_OR_METADATA",
}
H265_NAL_NAMES = {19:"IDR_W_RADL",20:"IDR_N_LP",21:"CRA_NUT",32:"VPS",33:"SPS",34:"PPS",35:"AUD"}
H264_NAL_NAMES = {1:"NON_IDR",5:"IDR",7:"SPS",8:"PPS",9:"AUD"}
